name: ElevatorSigns
author: Golfing8
version: 2.4.4
api-version: 1.13
main: com.golfing8.elevatorsigns.ElevatorSignsRevamped
commands:
  elevatorsigns:
    usage: '/elevatorsigns reload'
    description: 'Reloads the plugin''s config'
    aliases:
      - elevators
      - elevator
      - elevatorsign
      - esigns
      - esign